### ISSUE TITLE
Not running?

### ISSUE THREAD

**Issue by dlimanov** [putterpanda/mimikittenz#11]
Apologies if this is super dumb, but I've tried running mimikittenz on Win7 x64 SP1, Win8.1 and Win10 and in all cases nothing happens after executing the script:
PS C:\mimikittenz-master> .\Invoke-mimikittenz.ps1
PS C:\mimikittenz-master>
No error, no output, just nothing happens.
Does this script require a particular version of PowerShell or any other dependencies? 
Thanks!

**Comment by orlyjamie** [comment]
Hello dlimanov, 

I've tested now on Win8.1 x64 and have not noticed any issue. 

Does it just hang after the ASCII art? If that is the case it may still be searching in memory (The more browser tabs you have open, the longer it will take to complete the script) - _`Note: I've had it take up to 4-5 minutes with a lot of tabs open in Chrome.`_ 

In order to do more controlled testing you may want to limit the process scope by only targeting a single process in line `532`

`$matchesFound=[mimikittenz.MemProcInspector]::InspectManyProcs("chrome")`

**Comment by dlimanov** [comment]
Hi Putterpanda,
Thank you for replying! That's the thing, even the ASCII graphics don't load; it's like nothing happens whatsoever, as if PowerShell doesn't know what to do with the script. I'll check Event Viewer to see if there are any relevant events that hopefully will shed some light on this issue.

**Comment by dlimanov** [comment]
This is super weird, I just tried on both Win7 and 8.1 and while Event Viewer registers script execution (Event ID 4104, Source: PowerShell), still nothing is being displayed in the PowerShell command window (or ISE for that matter, I tried that as well); not ASCII, no errors, nothing.
You don't happen to have a video of the script executing on your system, do you?

**Comment by Dangles91** [comment]
Hey dilmanov, 

The ps1 file contains just the function itself and doesn't call it directly,  you'll need to modify the ps1 to also call the function, or dot source into a module file. 

Alternatively, you can remove the function header and closing curly brace and call the script file directly.

**Comment by orlyjamie** [comment]
@ dlimanov Ah hehe, did not even realize that you were not calling the function `Invoke-mimikittenz` (My bad)

The reason I wrote the script like this is because I plan to add additional functions to the script. 

If you want it to run the way your trying you can follow `Dangles91` recommendations _or_ you can simply add `Invoke-mimikittenz;` at the bottom of the script on it's own line.

**Comment by scopolamin** [comment]
==> #2 How to run it

---

PS C:> Set-ExecutionPolicy RemoteSigned
http://www.howtogeek.com/106273/how-to-allow-the-execution-of-powershell-scripts-on-windows-7/

---

3 options:

1) Call the function from the file (=> last line)

```
function Invoke-mimikittenz
{
  /* code */
  write-output $asciiart
  $matches=[mimikittenz.MemProcInspector]::InspectManyProcs("iexplore","chrome","firefox")

  write-output $matches
}

Invoke-mimikittenz
```

2) Invoke the functions from the file

PS C:> **powershell -command "& { . C:\foo\bar\Invoke-mimikittenz.ps1; Invoke-mimikittenz }"**

3) Load the file and call the function

PS C:\foo\bar> **.\Invoke-mimikittenz.ps1**
PS C:\foo\bar> **Invoke-mimikittenz**

**Comment by dlimanov** [comment]
Gosh do I feel stupid! Sorry to waste the time guys..

**Comment by Dangles91** [comment]
Haha all good mate, I might know powershell, but the reason I know what was wrong, is because I did the exact same thing XD

**Comment by orlyjamie** [comment]
No problem dlimanov, thanks for the feedback any way.

**Comment by E3V3A** [comment]
Please add this info to the README file. I wasted too much time to find this in a closed issue.

Also, please provide the output of `Get-ExecutionPolicy -List` when it **is** working.
