### ISSUE TITLE
Bad output

### ISSUE THREAD

**Issue by tristandostaler** [putterpanda/mimikittenz#4]
I don't know why, but in the output, there is still the formating text ex: {1,50} and no passwords.
ex:
Slack             &crumb=.{1,70}&email=.{1,50}&password=.{1,48}" ?y?? C?
Slack             &crumb=.{1,70}&email=.{1,50}&password=.{1,48}"  x<? X?blob-code blob-code-inner js-fi
CitrixNetScaler   login=.{1,32}&passwd=.{1,22}&PPSX="            ?z?? ??9(x#
CitrixNetScaler   login=.{1,32}&passwd=.{1,22}&PPSX="           ?z?? ?bgnkhhnn

**Comment by tieuhodo** [comment]
![powershell](https://cloud.githubusercontent.com/assets/10146355/16659124/08f3c92a-4493-11e6-8114-17fe651aad11.png)

**Comment by tieuhodo** [comment]
i login gmail, twitter, facebook and github on google chrome but result not found :)

**Comment by orlyjamie** [comment]
Hi Mate,

I've seen this happen when you browse to the github page before running the script  - this is because technically your putting these literal strings in memory by viewing them in the browser. Try kill the process, log in again to your target service and re-run the script without browsing to the mimikatz page.

**Comment by tristandostaler** [comment]
Thanks!
