### ISSUE TITLE
Truncated results

### ISSUE THREAD

**Issue by theabraxas** [putterpanda/mimikittenz#5]
Results all look like this:

PatternName                                                 PatternMatch                                               

---

CitrixNetScaler                                             login=.{1,22}&passwd=.{1,42}"xml   D      A       ?J   ...

The ellipses at the end for each line in the result, It happens both when I run it in terminal and > to output file. I assume there's some line/width buffer that can be increased? Would definitely be worth adding to the docs.

**Comment by kamakazikamikaze** [comment]
Same issue here, happens to _all_ output

**Comment by leesoh** [comment]
Same here.

**Comment by Pips801** [comment]
![powershell_2016-07-07_16-41-26](https://cloud.githubusercontent.com/assets/5651603/16672192/bf6ac186-4461-11e6-9b23-0ab946c9be0b.png)

Same here.

**Comment by Lemmmy** [comment]
See #4

**Comment by orlyjamie** [comment]
`[Non-issue]` - Victim user would never be browsing this github, if they are you already failed :laughing:

**Comment by ionrover2** [comment]
So was there any particular reason this was closed non issue?

**Comment by orlyjamie** [comment]
Hello ionrover2, please checkout `https://github.com/putterpanda/mimikittenz/issues/4` - For sake of explanation - The reason users are seeing this strange output is because they've viewed the powershell code from the same browser that they are dumping process memory from. 

In-case that's not self explanatory, the powershell code does not actually know what is a password and what is not, all it is doing is going through the memory space utilizing regular expressions - So it's actually doing it's job by picking these out. 

It was labelled as a `[Non-issue]` due to the fact that in a real-world scenario, these strings are not going to already exist within a victims browser process memory (Unless the victim user has been looking at this code in their browser before-hand) .. If the victim is looking at this code in their browser before you run the script - You've got bigger things to worry about :laughing:

**Comment by ionrover2** [comment]
That makes perfect sense. My bad.

**Comment by orlyjamie** [comment]
All good mate, thanks for double checking :+1:
